In [2]:
import plotly.offline as pyo
import plotly.graph_objs as go
import pandas as pd
import numpy as np

In [7]:
datos=pd.read_excel(r'C:\Users\rodrigo.villanueva.c\Documents\TODO_PYTHON\Curso_Ploty-dash\Datasets\3.8\Temperaturas.xlsx')

datos.head(50)

        FECHA  Ciudad  T, Máxima  T,Mínima  T_Promedio
0  2019-06-01  Madrid       33.1      17.2       25.15
1  2019-06-02  Madrid       34.5      19.0       26.75
2  2019-06-03  Madrid       32.8      20.3       26.55
3  2019-06-04  Madrid       29.0      18.9       23.95
4  2019-06-05  Madrid       22.1      12.7       17.40
5  2019-06-06  Madrid       24.0      11.0       17.50
6  2019-06-07  Madrid       22.0       9.0       15.50
7  2019-06-08  Madrid       29.2      12.8       21.00
8  2019-06-09  Madrid       27.7      14.2       20.95
9  2019-06-10  Madrid       26.4      14.7       20.55
10 2019-06-11  Madrid       21.0      14.0       17.50
11 2019-06-12  Madrid       25.4      10.0       17.70
12 2019-06-13  Madrid       28.5      14.4       21.45
13 2019-06-14  Madrid       25.5      14.9       20.20
14 2019-06-15  Madrid       25.7      12.0       18.85
15 2019-06-16  Madrid       28.6      14.5       21.55
16 2019-06-17  Madrid       32.0      16.0       24.00
17 2019-06-18  Madrid       31.3      19.2       25.25
18 2019-06-19  Madrid       27.0      18.0       22.50
19 2019-06-20  Madrid       28.5      17.5       23.00
20 2019-06-21  Madrid       29.6      17.7       23.65
21 2019-06-22  Madrid       31.4      16.8       24.10
22 2019-06-23  Madrid       33.4      18.5       25.95
23 2019-06-24  Madrid       32.0      21.3       26.65
24 2019-06-25  Madrid       34.2      19.3       26.75
25 2019-06-26  Madrid       35.5      22.5       29.00
26 2019-06-27  Madrid       38.5      22.7       30.60
27 2019-06-28  Madrid       40.7      24.0       32.35
28 2019-06-29  Madrid       40.0      24.5       32.25
29 2019-06-30  Madrid       38.5      25.0       31.75
30 2019-07-01  Madrid       36.3      23.8       30.05
31 2019-07-02  Madrid       35.5      23.0       29.25
32 2019-07-03  Madrid       35.2      22.0       28.60
33 2019-07-04  Madrid       33.2      23.1       28.15
34 2019-07-05  Madrid       33.7      21.6       27.65
35 2019-07-06  Madrid       34.9      19.7       27.30
36 2019-07-07  Madrid       34.5      19.5       27.00
37 2019-07-08  Madrid       30.8      19.5       25.15
38 2019-07-09  Madrid       30.1      17.5       23.80
39 2019-07-10  Madrid       33.1      18.2       25.65
40 2019-07-11  Madrid       37.0      20.8       28.90
41 2019-07-12  Madrid       38.8      24.2       31.50
42 2019-07-13  Madrid       35.0      24.1       29.55
43 2019-07-14  Madrid       33.1      21.6       27.35
44 2019-07-15  Madrid       35.6      20.4       28.00
45 2019-07-16  Madrid       36.8      22.0       29.40
46 2019-07-17  Madrid       34.2      22.6       28.40
47 2019-07-18  Madrid       35.7      21.5       28.60
48 2019-07-19  Madrid       37.1      23.1       30.10
49 2019-07-20  Madrid       37.3      24.4       30.85

In [6]:
data=[go.Box(
    x=datos["Ciudad"],
    y=datos["T_Promedio"]
)]


layout=go.Layout(title="Box and Temperatura")

fig=go.Figure(data=data,layout=layout)

pyo.plot(fig, filename="Box_temperatura.html")

'Box_temperatura.html'